name: CI

on:
  release:
    types: [ published ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Install testing dependencies
        run: npm install concurrently http-server wait-on
      - name: Run tests
        run: npx concurrently -k -s first -n "Storybook,Component Tests" -c "bgGray.white,auto" \ "npx http-server storybook-static --port 6006 --silent" \ "npx wait-on tcp:6006 && npm test" \
  build:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
      - name: Build app
        run: npm ci && npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Setup npmrc
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Deploy to npm
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
