name: Update cache

on:
  push:
    branches:
      - main
env:
  FORCE_COLOR: 1
jobs:
  update_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
          cache-dependency-path: .dependency-version
          registry-url: 'https://registry.npmjs.org'
      - name: Get dependency version
        id: dependency-version
        run: |
          echo "DEPENDENCY_VERSION=$(cat .dependency-version)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ steps.dependency-version.outputs.DEPENDENCY_VERSION }}
      - name: Cache Playwright
        id: cache-playwright
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ steps.dependency-version.outputs.DEPENDENCY_VERSION }}
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install
